//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineManagementSystemOOAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airline
    {
        public Airline()
        {
            this.Booking_Details = new HashSet<Booking_Details>();
        }
    
        public int Airline_ID { get; set; }
        public string Airline_Name { get; set; }
        public string Details { get; set; }
    
        public virtual ICollection<Booking_Details> Booking_Details { get; set; }
    }
}
