//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineManagementSystemOOAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Details
    {
        public int Detail_Id { get; set; }
        public Nullable<int> Airline_ID { get; set; }
        public Nullable<int> Airport_ID { get; set; }
        public Nullable<int> Booking_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Time_Period_ID { get; set; }
        public int Total { get; set; }
        public string Details { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual Airport Airport { get; set; }
        public virtual Booking Booking { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual TimePeriod TimePeriod { get; set; }
    }
}
