//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineManagementSystemOOAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Booking_Details = new HashSet<Booking_Details>();
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Customer_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string C_Password { get; set; }
        public string Orgazanization { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string Gender { get; set; }
        public string Details { get; set; }
    
        public virtual ICollection<Booking_Details> Booking_Details { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
