 //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineManagementSystemOOAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketBook
    {
        public int n;
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Gender { get; set; }
        public Nullable<long> CNIC { get; set; }
        public Nullable<long> Phone { get; set; }
        public string FlyingFrom { get; set; }
        public string FlyingTo { get; set; }
        public string Dept { get; set; }
        public string Returning { get; set; }
        public Nullable<int> Adults { get; set; }
        public Nullable<int> Child { get; set; }
        public string FClass { get; set; }
        public Nullable<int> SeatsAvailable { get; set; }
        public Nullable<int> TotalAmount { get; set; }

        
    }
}
